version: '3'
services:
  mysql:
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'flightsearch'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '4306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: